version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ng_cash
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: ng_cash_db

volumes:
  pgdata:
